feat(VRoadizLink): add data reactivity
rezozero/nuxt-starter pull request #147
Opened 2024-10-31 13:17 UTC by timothejoubert

2024-11-05 08:02 UTC, manuelodelain requested changes

2024-11-05 08:02 UTC, manuelodelain commented on components/molecules/VRoadizLink/VRoadizLink.vue
> +            const attrsMerged = { ...attrs, ...props.nuxtLinkProps }
`attrsMerged` => `mergedAttrs` or `result`

2024-11-05 08:02 UTC, manuelodelain commented on components/molecules/VRoadizLink/VRoadizLink.vue
> +            if (!url.value || props.custom) {
custom render should be triggered only by the `custom` prop (no exception)

2024-11-05 08:02 UTC, manuelodelain commented on utils/url.ts
why deleting this function? It can be useful

2024-11-26 10:30 UTC, timothejoubert commented
this PR resolve this issue https://github.com/rezozero/nuxt-starter/issues/170

2024-11-26 10:35 UTC, manuelodelain approved these changes

2024-11-26 10:35 UTC, merged