feat: update i18n module and adapt config folder and trad files
rezozero/nuxt-starter pull request #203
Opened 2024-12-12 15:30 UTC by timothejoubert

2024-12-12 16:15 UTC, timothejoubert commented
- [ ]  i18n locale data don't persist SSR/client

2024-12-18 08:20 UTC, manuelodelain requested changes

2024-12-18 08:20 UTC, manuelodelain commented on nuxt.config.ts
> +                    file: `nuxt.${locale}.default.json`,
I don't think it's a good idea to split translations into multiple files. The default file won't be available into xilofone

2024-12-18 08:20 UTC, manuelodelain commented on utils/locale.ts
> +}
We should only rely on Nuxt I18n at runtime, not on constants. All the available translations are available on `$i18n.locales`

2025-01-10 16:00 UTC, Illawind approved these changes

2025-01-10 16:04 UTC, manuelodelain approved these changes

2025-01-10 16:04 UTC, merged