Refactor(VButton): Clean component for simplify usage
rezozero/nuxt-starter pull request #54
Opened 2024-09-18 08:41 UTC by timothejoubert

2024-09-18 15:31 UTC, manuelodelain requested changes

2024-09-18 15:31 UTC, manuelodelain commented on components/molecules/VButton/VButton.vue
> +        const { isRelative, isExternal, url } = usePathLinkParser(props.to)
Maybe we should use `useLink` from VueRouter here? instead of re-developing our own logic here

2024-09-19 13:45 UTC, timothejoubert commented on components/molecules/VButton/VButton.vue
> +        const { isRelative, isExternal, url } = usePathLinkParser(props.to)
I made some changes,  

I tried to merge to and href prop, and convert external link which have same siteUrl to relative path. 
I achieved this to uniform prop usage and url output through the app.

2024-09-20 08:00 UTC, manuelodelain approved these changes

2024-09-20 08:00 UTC, merged